#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

SOURCE="$REPO_ROOT/scripts/credential-capture-root.sh"
TARGET="/usr/local/libexec/wormlogic/credential-capture-root"
SUDOERS_TARGET="/etc/sudoers.d/wormlogic-credential-capture"

USER_NAME="$(id -un)"

[[ -f "$SOURCE" ]] || {
  echo "ERROR: missing helper source: $SOURCE" >&2
  exit 1
}

command -v sudo >/dev/null 2>&1 || {
  echo "ERROR: sudo is required" >&2
  exit 1
}

[[ -x /usr/sbin/visudo ]] || {
  echo "ERROR: /usr/sbin/visudo not found" >&2
  exit 1
}

sudo install -d \
  -o root \
  -g root \
  -m 0755 \
  /usr/local/libexec/wormlogic

sudo install \
  -o root \
  -g root \
  -m 0755 \
  "$SOURCE" \
  "$TARGET"

tmp="$(mktemp)"
trap 'rm -f -- "$tmp"' EXIT

cat > "$tmp" <<EOF
# Generated by linux-environments/scripts/install-credential-capture-helper.sh
${USER_NAME} ALL=(root) NOPASSWD: ${TARGET} *
EOF

sudo /usr/sbin/visudo -cf "$tmp"

sudo install \
  -o root \
  -g root \
  -m 0440 \
  "$tmp" \
  "$SUDOERS_TARGET"

echo "✓ Credential-capture privilege helper installed"
echo "  helper:  $TARGET"
echo "  sudoers: $SUDOERS_TARGET"
