#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

ROOT_SOURCE="$REPO_ROOT/scripts/system-update-root.sh"
AUR_SOURCE="$REPO_ROOT/scripts/system-update-aur-sudo.sh"

ROOT_TARGET="/usr/local/libexec/wormlogic/system-update-root"
AUR_TARGET="/usr/local/bin/wormlogic-update-sudo"
SUDOERS_TARGET="/etc/sudoers.d/wormlogic-system-update"

USER_NAME="$(id -un)"

for file in "$ROOT_SOURCE" "$AUR_SOURCE"; do
  [[ -f "$file" ]] || {
    echo "ERROR: missing source: $file" >&2
    exit 1
  }
done

command -v sudo >/dev/null 2>&1 || {
  echo "ERROR: sudo is required" >&2
  exit 1
}

[[ -x /usr/sbin/visudo ]] || {
  echo "ERROR: /usr/sbin/visudo not found" >&2
  exit 1
}

sudo install -d -o root -g root -m 0755 \
  /usr/local/libexec/wormlogic

sudo install -o root -g root -m 0755 \
  "$ROOT_SOURCE" \
  "$ROOT_TARGET"

sudo install -o root -g root -m 0755 \
  "$AUR_SOURCE" \
  "$AUR_TARGET"

tmp="$(mktemp)"
trap 'rm -f -- "$tmp"' EXIT

cat > "$tmp" <<EOF
# Generated by linux-environments/scripts/install-system-update-helper.sh
${USER_NAME} ALL=(root) NOPASSWD: ${ROOT_TARGET} *
EOF

sudo /usr/sbin/visudo -cf "$tmp"

sudo install -o root -g root -m 0440 \
  "$tmp" \
  "$SUDOERS_TARGET"

echo "✓ System update privilege helper installed"
echo "  root helper: $ROOT_TARGET"
echo "  AUR sudo:    $AUR_TARGET"
echo "  sudoers:     $SUDOERS_TARGET"
