#!/usr/bin/env bash
set -euo pipefail

VPN_USER="${SUDO_USER:-${USER:-}}"
TARGET="/etc/sudoers.d/wormlogic-vpn"

if [[ -z "$VPN_USER" || "$VPN_USER" == "root" ]]; then
    echo "✗ Run this helper as the normal workstation user, not from a root shell." >&2
    exit 1
fi

for command_name in sudo visudo install mktemp; do
    command -v "$command_name" >/dev/null 2>&1 || {
        echo "✗ Required command not found: $command_name" >&2
        exit 1
    }
done

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

cat >"$tmp" <<EOF
# Wormlogic/PVP VPN helper permissions.
# Generated by linux-environments/scripts/install-wireguard-sudoers.sh

Cmnd_Alias WORMLOGIC_VPN_SYSTEMD = \\
    /usr/bin/systemctl start wg-quick@wormlogic.service, \\
    /usr/bin/systemctl stop wg-quick@wormlogic.service, \\
    /usr/bin/systemctl start wg-quick@wg-pvp.service, \\
    /usr/bin/systemctl stop wg-quick@wg-pvp.service

Cmnd_Alias WORMLOGIC_VPN_WG_READ = \\
    /usr/bin/wg show wormlogic, \\
    /usr/bin/wg show wg-pvp, \\
    /usr/bin/wg show wg-pvp peers, \\
    /usr/bin/wg show wg-pvp endpoints, \\
    /usr/bin/wg show wg-pvp latest-handshakes

Cmnd_Alias WORMLOGIC_VPN_WG_SET = \\
    /usr/bin/wg ^set wg-pvp peer [A-Za-z0-9+/=]+ endpoint (([0-9]{1\\,3}\\.){3}[0-9]{1\\,3}:51821|127\\.0\\.0\\.1:51822)\$

Cmnd_Alias WORMLOGIC_VPN_IP = \\
    /usr/bin/ip ^rule (add|del) priority 10000 to ([0-9]{1\\,3}\\.){3}[0-9]{1\\,3}/32 table main\$, \\
    /usr/bin/ip link set dev wg-pvp mtu 1300

$VPN_USER ALL=(root) NOPASSWD: WORMLOGIC_VPN_SYSTEMD, WORMLOGIC_VPN_WG_READ, WORMLOGIC_VPN_WG_SET, WORMLOGIC_VPN_IP
EOF

sudo visudo -cf "$tmp"
sudo install -o root -g root -m 0440 "$tmp" "$TARGET"
echo "✓ WireGuard sudo authorization installed: $TARGET"
